[General]
__userfile__=true
iconTheme=Papirus-Light

[fancymenu]
favorites\1\desktopFile=/usr/share/applications/featherpad.desktop
favorites\2\desktopFile=/usr/share/applications/lubuntu-update.desktop
favorites\3\desktopFile=/usr/share/applications/pcmanfm-qt.desktop
favorites\4\desktopFile=/usr/share/applications/qterminal.desktop
favorites\5\desktopFile=/usr/share/applications/org.kde.falkon.desktop
favorites\6\desktopFile=/usr/share/guake/autostart-guake.desktop
favorites\size=6

[mount]
alignment=Right

[panel1]
alignment=-1
animation-duration=0
background-color=@Variant(\0\0\0\x43\0\xff\xff\0\0\0\0\0\0\0\0)
background-image=
desktop=0
font-color=@Variant(\0\0\0\x43\0\xff\xff\0\0\0\0\0\0\0\0)
hidable=false
hide-on-overlap=false
iconSize=28
lineCount=1
lockPanel=false
opacity=100
panelSize=29
plugins=fancymenu, quicklaunch, taskbar, sysstat, mount, volume, tray, statusnotifier, worldclock, showdesktop
position=Bottom
reserve-space=true
show-delay=0
visible-margin=true
width=100
width-percent=true

[quicklaunch]
apps\1\desktop=/usr/share/applications/pcmanfm-qt.desktop
apps\2\desktop=/usr/share/applications/featherpad.desktop
apps\3\desktop=/var/lib/snapd/desktop/applications/firefox_firefox.desktop
apps\4\desktop=/usr/share/applications/vlc.desktop
apps\5\desktop=/usr/share/applications/qterminal-drop.desktop
apps\6\desktop=/usr/share/applications/gimp.desktop
apps\7\desktop=/usr/share/applications/org.kde.discover.desktop
apps\size=7

[sysstat]
alignment=Right
cpu\useFrequency=true
data\source=cpu
data\type=CPU
graph\minimalSize=44
graph\updateInterval=2
graph\useThemeColours=true
grid\lines=0
net\logarithmicScale=true
net\logarithmicScaleSteps=4
net\maximumSpeed=1 MB/s
title\label=
type=sysstat

[taskbar]
alignment=Left

[tray]
alignment=Right

[volume]
alignment=Right

[worldclock]
alignment=Right
autoRotate=true
customFormat="'<b>'HH:mm '</b><font size=\"-1\">' ddd d MMM yy'</font>'"
dateFormatType=long
dateLongNames=false
datePadDay=false
datePosition=before
dateShowDoW=false
dateShowYear=false
defaultTimeZone=
formatType=custom-timeonly
showDate=true
showTimezone=false
showTooltip=false
showWeekNumber=true
timeAMPM=false
timePadHour=false
timeShowSeconds=false
timeZoneWheel=true
timeZones\size=0
timezoneFormatType=iana
timezonePosition=below
useAdvancedManualFormat=true
