printf %b '\e[K  /\_/\'; 
printf %b '\e[K (0 . 0)'; 
printf %b '\e[K   · ·'; 
sleep .2; printf %b "\e[4A"; 
printf %b '\e[K  /\_/\'; 
printf %b '\e[K (0 . 0)'; 
printf %b '\e[K   \' ·'; 
sleep .2; printf %b "\e[4A"; 
printf %b '\e[K  /\_/\'; 
printf %b '\e[K (0 . 0)'; 
printf %b '\e[K   · \''; 
sleep .2; printf %b "\e[4A"; 
printf %b '\e[K  /\_/\'; 
printf %b '\e[K (0 . 0)'; 
printf %b '\e[K   \' .'; 
sleep .2; printf %b "\e[4A"; 
printf %b '\e[K  /\_/\'; 
printf %b '\e[K (0 . -)'; 
printf %b '\e[K   . \''; 
sleep .2; printf %b "\e[4A"; 
printf %b '\e[K  /\_/\'; 
printf %b '\e[K (- . -)'; 
printf %b '\e[K   · ·'; 
sleep .2; printf %b "\e[4A"; 
printf %b '\e[K  /\_/\'; 
printf %b '\e[K (0 = 0)'; 
printf %b '\e[K   · ·'; 
sleep .2; printf %b "\e[4A"; 
printf %b '\e[K  /\_/\'; 
printf %b '\e[K (0 . 0)'; 
printf %b '\e[K   · ·'; 
sleep .2; printf %b "\e[4A"; 
printf %b '\e[K  /\_/\'; 
printf %b '\e[K (0 O 0)'; 
printf %b '\e[K   . .'; 
sleep .2; printf %b "\e[4A"; 
printf %b '\e[K  _\^ \^_'; 
printf %b '\e[K (0() 0)'; 
printf %b '\e[K   . .'; 
sleep .2; printf %b "\e[4A"; 
printf %b '\e[K  /\_/\'; 
printf %b '\e[K (0 . 0)'; 
printf %b '\e[K   · ·'; 
sleep .2; printf %b "\e[4A"; 
printf %b '\e[K  /\_/\'; 
printf %b '\e[K (0 @ 0)'; 
printf %b '\e[K   ∆ ∆'; 
sleep .2; printf %b "\e[4A"; 
printf %b '\e[K  /\_/\'; 
printf %b '\e[K (0 . 0)'; 
printf %b '\e[K   · ·'; 
sleep .2; printf %b "\e[4A"; 
