#!/data/data/com.termux/files/usr/bin/bash
export url="$1"; line='\e[2m-------------------\e[0m'; 
dir=/sdcard/Downloads/ig; mkdir $dir/tmp -p 2>/dev/null; 
mkdir $HOME/logs 2>/dev/null; 
##
echo >> $HOME/logs/urlinks.url; 
printf %b "${line}\n$(date +%x\ -\ %X)\n${line}\n$url"|tee -a $HOME/logs/urlinks.url; 
printf %b "\n${line}\n"; 
dl_insta() {
# printf %b "\n\n------\n$time\n$1"|tee -a ~/logs/urlinks.url;
# echo $1|tee -a ~/logs/urlinks.url; 
time="$(date +%y%m%d%H%M%S)"; dlf="/sdcard/Downloads/ig"; termux-notification -c "$(time="$(date +%y%m%d%H%M%S)"; dlf="/sdcard/Downloads/ig"; yt-dlp --output "$time" -P "$dlf" "$(tail -n1 ~/logs/urlinks.url)" --quiet 2>/dev/null; ffmpeg -i $dlf/$(ls -t1 $dlf|head -n1) $dlf/tmp/$time.jpg -y 2>/dev/null)" --image-path "$dlf/tmp/$time.jpg" --action "xdg-open $dlf/$time.mp4" -t "$dlf/$time" & 

# [ -z $url ] && url="$1"; dir=/sdcard/Downloads/ig; 
# nohup yt-dlp --restrict-filenames -P "$dir" "$url" 2>/dev/null >> tee -a ~/logs/lu.log;  
# nyt="$dir/$(ls -1tr $dir|tail -n1)"; 
# ffmpegthumbnailer -i "$nyt" -o "$nyt.jpg"; 
# (termux-notification --image-path "$nyt.jpg" --action "xdg-open "$nyt"" -t "${nyt/*\//}";
##
# rm "$nyt.jpg"; 
# exit 0; 
# echo "----"; ) & 
##
##
##
}; 
# cd /storage/emulated/0/Pictures; pwd; 
if [ $(printf %b "$url"|grep -e "instagram") ]; 
then 
dl_insta $url; echo ok; 
else 
#
printf %b "\n${line}\n"; 
. $HOME/bin/dfree.sh; 
printf %b "${line}\n"; 
# yt-dlp --restrict-filenames "$url" && termux-notification --action 'termux-open $pp' -c "gg" || termux-storage-get; exit 0; fi; 
# pp="$(realpath $(ls -t /sdcard/Pictures/*.mp4|head -n1))"; 
# --paths /storage/emulated/0/Pictures; 
# termux-media-scan -r /storage/emulated/0/Pictures; 
# python $HOME/bin/igdl/igdl.py "$1" && nf="$(realpath $(command ls -t /sdcard/Pictures/igdl|head -n1))" && 
 # && termux-notification -c "$nf" --action 'termux-open $nf' && exit 0; 
## selection menu
qqmenu() { local IFS=$'\n\t ';local ops=($2);[ "$2" ]||local ops=(*);
local prompt="$1" index="0" cur="0" count="${#ops[@]}" esc=$(echo -ne "\e");
printf "\e[?25l    -- $prompt --\n\n"; ## print prompt
while true; do local index="0"; for o in "${ops[@]}"; ## print options
do if [ "$index" == "$cur" ];
then printf %b "\e[0m > \e[7m $o \e[0m\e[K\n"; ## mark & highlight the current option
else printf %b "\e[0m    $o  \e[K\n";
fi; (( index++ ));
done; ## list all options (option list is zero-based)
read -srn1 key; ## wait for user to key in arrows or ENTER
if [[ "$key" == A ]]; then (( cur-- )); (( cur < 0 ))&& (( cur = 0 ));
elif [ "$key" == B ]; then (( cur++ )); (( cur >= count )) && (( cur = count - 1 ));
elif [[ $key == C ]]; then mark+=(${ops[$cur]});
printf %b "\e[s\e[6;22H\e[K${mark[@]}\e[K\e[u";
elif [[ $key == "" ]]; then break;
elif [[ $key == "q" ]]; then exit; fi; # enter
echo -en "\e[${count}A"; done; # go up to the beginning to re-render
##
##
printf -v sel "${ops[$cur]}"; printf  "\e[?25h\n \e[7m $sel \e[0m\n\n"; }; 
####################
[ -w $HOME/sd2/Alarms ] && dir="$HOME/sd2/Alarms" || dir="$HOME/storage/downloads/"; 
####################
printf %b "$url"|bat -ppfld; printf %b "\n-\e[$((COLUMNS - 1))b\n\n"; 
####################
qqmenu "what to do?" "yt-dlp xdg-open aria2c"; 
####################
printf %b "\n whereto? 
 ${line}
 -- [E]xternal - alarms
 -- [L]ocal    - downloads
 -- [C]hoose   - lf
 -- [F]hoose   - read
 -- [H]ere     - $dir
 ${line} \n"|col|bat -ppflgo;  
read -srn1 "wt"; 
case $wt in 
e) dir="$HOME/external/Alarms";;
l) dir="$HOME/sdcard/Downloads";;
c) dir="$(command lf -print-last-dir)";; 
f) read -ri "$HOME/" dir;; 
h|*) printf %b "ok\n";; 
q) return;; esac; 
####################
case $sel in 
yt-dlp) dl_insta;; 
aria2c) aria2c -d "$dir" "$url";; 
save-link-url) printf %b "\n$url\n"|tee -a ${dir}/links.url;
printf %b "\n\n  saved to: \n  ${dir}/links.url\n\n  ok\n"; sleep 1;; 
# mkdir $HOME/links 2>/dev/null; 
esac; 

## 


dfree() { 
local IFS=$'\n\t '; 
if [ $PREFIX ]; 
then df=($(df -h|rg -e "sdcard/default|storage|Size"|tr -s " " " "|cut -f2,4,5,6 -d" ")); 
else df=($(df -h|rg -v "efi|tmpfs|\*tmpfs|9p|fonts|none|run| 0 "|tr -s " " " "|cut -f2,4,5,6 -d" ")); 
fi; 
plup='■'; 
aa=0; kk=0; a=0; as=1; dflines="$((${#df[*]} / 4))"; 
dk=(028 114 151 152 247 143 220 209 200 196); 
#####
#####
for i in ${df[*]}; do \
for a in {3,0,1,2}; do \
disk="$(printf %b "${df[((a+aa))]}")"; 
[ ${disk} ] && printf %b "${disk} "|bat -ppflc --theme zenburn;  
((kk++)); done; 
# | bat -ppfljava --theme DarkNeon; 
##
[ $((kk / 4 - 1)) -lt $dflines ] && \
[ $aa -gt 0 ] && \
(sa="${df[((a+aa))]}"; 
####
[ ${#sa} -gt 1 ] && as=${sa:0:1}; 
## percent in number
####
# printf %b " "; 
# printf %b "\e[37;2m"; 
# for p in {0..9}; do printf %b "$plup"; done; printf %b "\e[0m\e[10D"; 
# for i in {0..9}; do printf %b "\e[37;2m▇\e[0m"; done; 
# printf %b "\e[12D "; 
printf %b "\e[38;5;237m■■■■■■■■■■\e[0m\e[10D"; 
for i in $(seq $as); do 
printf %b "\e[38;5;${dk[as]}m${plup}\e[0m"; 
done; ); 
####
aa=$kk; printf %b "\n"; done | 
column --separator=" " --table --table-columns-limit 5 \
--output-separator "$(printf %b "\e[37;2m | \e[0m")";
# | bat -ppfljava; 
}; 



fi; 

