[General]
bgColor=@Variant(\0\0\0\x43\x1\xff\xff\xbe\xbe\xbe\xbe\xbe\xbe\0\0)
fallbackIconTheme=oxygen
fullScreenBgColor=@Variant(\0\0\0\x43\x1\xff\xff\"\"\"\"\"\"\0\0)
maxRecentFiles=5
recentlyOpenedFiles=/home/aa/640916461_17866869963571349_4268358071536495728_n.jpg, /home/aa/Pictures/kk.jpg, /home/aa/Pictures/sdsd.jpg, /home/aa/Pictures/tanya-barrow-ESAj3x0OvVI-unsplash.jpg, /home/aa/Pictures/kristina-bekher-FvZIK5lIGaU-unsplash.jpg
slideShowInterval=5
sorting=name

[Thumbnail]
MaxThumbnailFileSize=4096
ShowThumbnails=true
ThumbnailSize=64
ThumbnailsPosition=bottom

[Window]
ColorSpace=1
ExifDatakWidth=250
FixedHeight=480
FixedWidth=640
ForceZoomFit=true
LastWindowHeight=768
LastWindowMaximized=true
LastWindowWidth=1366
PrefSize=@Size(586 400)
ShowAnnotationsToolbar=true
ShowExifData=false
ShowMenubar=true
ShowOutline=true
ShowToolbar=true
SmoothOnZoom=true
UseTrash=true
