#!/bin/bash
#Here's a list of 122 interesting English words, formatted as a bash array. Each element in the `interesting_words` array is a string containing the word, its phonetic transcription (IPA), its part of speech (type), and its meaning, separated by `|` characters.

#```bash
#!/bin/bash

# This array contains a list of interesting English words.
# Each element is formatted as "Word|Phonetic|Type|Meaning".
# The phonetic transcriptions are in IPA (International Phonetic Alphabet).
# Type abbreviations: n. (noun), v. (verb), adj. (adjective), adv. (adverb).
declare -a interesting_words=(
  "Serendipity|/ˌsɛrənˈdɪpɪti/|n.|The occurrence and development of events by chance in a happy or beneficial way."
  "Ephemeral|/ɪˈfɛmərəl/|adj.|Lasting for a very short time."
  "Petrichor|/ˈpɛtrɪkɔːr/|n.|The distinctive smell of rain on dry earth."
  "Limerence|/ˈlɪmərəns/|n.|The state of being infatuated with another person, typically involuntarily and characterized by a desire for reciprocation."
  "Mellifluous|/mɛˈlɪfluəs/|adj.|(Of a voice or words) sweet or musical; pleasant to hear."
  "Sonder|/ˈsɒndər/|n.|The realization that each random passerby is living a life as vivid and complex as your own."
  "Luminescence|/ˌluːmɪˈnɛsəns/|n.|The emission of light by a substance not resulting from heat; light from a chemical or biological reaction."
  "Aurora|/ɔːˈrɔːrə/|n.|A natural electrical phenomenon characterized by the appearance of streamers of reddish or greenish light in the sky, especially near the northern or southern magnetic poles."
  "Crepuscular|/krɪˈpʌskjələr/|adj.|Of, relating to, or resembling twilight; active in the twilight."
  "Zephyr|/ˈzɛfər/|n.|A soft, gentle breeze."
  "Clandestine|/klænˈdɛstɪn/|adj.|Kept secret or done secretively, especially because illicit."
  "Ubiquitous|/juːˈbɪkwɪtəs/|adj.|Present, appearing, or found everywhere."
  "Ethereal|/ɪˈθɪəriəl/|adj.|Extremely delicate and light in a way that seems too perfect for this world."
  "Languid|/ˈlæŋɡwɪd/|adj.|(Of a person, manner, or gesture) having a disinclination for physical exertion or effort; slow and relaxed."
  "Halcyon|/ˈhælsɪən/|adj.|Denoting a period of time in the past that was idyllically happy and peaceful."
  "Scintilla|/sɪnˈtɪlə/|n.|A tiny trace or spark of a specified quality or feeling."
  "Quixotic|/kwɪkˈsɒtɪk/|adj.|Exceedingly idealistic; unrealistic and impractical."
  "Cacophony|/kəˈkɒfəni/|n.|A harsh, discordant mixture of sounds."
  "Euphony|/ˈjuːfəni/|n.|The quality of being pleasing to the ear, especially through a harmonious combination of words."
  "Nefarious|/nɪˈfɛəriəs/|adj.|(Typically of an action or activity) wicked or criminal."
  "Egregious|/ɪˈɡriːdʒəs/|adj.|Outstandingly bad; shocking."
  "Salient|/ˈseɪliənt/|adj.|Most noticeable or important."
  "Innocuous|/ɪˈnɒkjuəs/|adj.|Not harmful or offensive."
  "Obsequious|/əbˈsiːkwiəs/|adj.|Excessively obedient or attentive to an excessive degree."
  "Perfunctory|/pəˈfʌŋktəri/|adj.|(Of an action or gesture) carried out with a minimum of effort or reflection."
  "Recalcitrant|/rɪˈkælsɪtrənt/|adj.|Having an obstinately uncooperative attitude toward authority or discipline."
  "Sagacious|/səˈɡeɪʃəs/|adj.|Having or showing keen mental discernment and good judgment; shrewd."
  "Taciturn|/ˈtæsɪtɜːrn/|adj.|(Of a person) reserved or uncommunicative in speech; saying little."
  "Vicarious|/vɪˈkɛəriəs/|adj.|Experienced in the imagination through the feelings or actions of another person."
  "Surreptitious|/ˌsʌrəpˈtɪʃəs/|adj.|Kept secret, especially because it would not be approved of."
  "Convivial|/kənˈvɪviəl/|adj.|(Of an atmosphere or event) friendly, lively, and enjoyable; (of a person) cheerful and friendly."
  "Desultory|/ˈdɛsəltəri/|adj.|Lacking a plan, purpose, or enthusiasm; aimless."
  "Fastidious|/fæsˈtɪdiəs/|adj.|Very attentive to and concerned about accuracy and detail; hard to please."
  "Garrulous|/ˈɡærʊləs/|adj.|Excessively talkative, especially on trivial matters."
    "Incipient|/ɪnˈsɪpiənt/|adj.|In an initial stage; beginning to happen or develop."
    "Laconic|/ləˈkɒnɪk/|adj.|(Of a person, speech, or style of writing) using very few words."
    "Magnanimous|/mæɡˈnænɪməs/|adj.|Generous or forgiving, especially toward a rival or less powerful person."
    "Nascent|/ˈnæsənt/|adj.|(Especially of a social phenomenon) just coming into existence and beginning to display signs of future potential."
    "Obstreperous|/əbˈstrɛpərəs/|adj.|Noisy and difficult to control."
    "Pellucid|/pəˈluːsɪd/|adj.|Translucently clear; easily understood."
    "Quiescent|/kwiˈɛsənt/|adj.|In a state or period of inactivity or dormancy."
    "Recondite|/ˈrɛkəndaɪt/|adj.|(Of a subject or knowledge) little known; abstruse."
    "Sanguine|/ˈsæŋɡwɪn/|adj.|Optimistic or positive, especially in an apparently bad or difficult situation."
    "Truculent|/ˈtrʌkjʊlənt/|adj.|Eager or quick to argue or fight; aggressively defiant."
    "Uxorious|/ʌkˈsɔːriəs/|adj.|Having or showing an excessive fondness for one's wife."
    "Vicissitude|/vɪˈsɪsɪtjuːd/|n.|A change of circumstances or fortune, typically one that is unwelcome or unpleasant."
    "Winsome|/ˈwɪnsəm/|adj.|Attractive or appealing in a fresh, innocent way."
    "Zenith|/ˈzɛnɪθ/|n.|The point in the sky or celestial sphere directly above an observer; the time at which something is most powerful or successful."
    "Nadir|/ˈneɪdɪər/|n.|The lowest point in the fortunes of a person or organization."
    "Penultimate|/pɪˈnʌltɪmət/|adj.|Last but one in a series of things; second to last."
    "Prevaricate|/prɪˈværɪkeɪt/|v.|Speak or act in an evasive way."
    "Repudiate|/rɪˈpjuːdieɪt/|v.|Refuse to accept or be associated with; deny the truth or validity of."
    "Stentorian|/stɛnˈtɔːriən/|adj.|(Of a person's voice) loud and powerful."
    "Punctilious|/pʌŋkˈtɪliəs/|adj.|Showing great attention to detail or correct behavior."
    "Alacrity|/əˈlækrɪti/|n.|Brisk and cheerful readiness."
    "Ameliorate|/əˈmiːljəreɪt/|v.|Make (something bad or unsatisfactory) better."
    "Capricious|/kəˈprɪʃəs/|adj.|Given to sudden and unaccountable changes of mood or behavior."
    "Deleterious|/ˌdɛlɪˈtɪəriəs/|adj.|Causing harm or damage."
    "Disparate|/ˈdɪspərət/|adj.|Essentially different in kind; not able to be compared."
    "Enervate|/ˈɛnərveɪt/|v.|Cause (someone) to feel drained of energy or vitality; weaken."
    "Equivocate|/ɪˈkwɪvəkeɪt/|v.|Use ambiguous language so as to conceal the truth or avoid committing oneself."
    "Expurgate|/ˈɛkspərɡeɪt/|v.|Remove objectionable passages or words from (a book or account)."
    "Fatuous|/ˈfætjuəs/|adj.|Silly and pointless."
    "Gregarious|/ɡrɪˈɡɛəriəs/|adj.|(Of a person) fond of company; sociable."
    "Harangue|/həˈræŋ/|n.|A lengthy and aggressive speech."
    "Hegemony|/hɪˈdʒɛməni/|n.|Leadership or dominance, especially by one state or social group over others."
    "Ignominious|/ˌɪɡnəˈmɪniəs/|adj.|Deserving or causing public disgrace or shame."
    "Impasse|/ˈɪmpæs/|n.|A situation in which no progress is possible, especially because of disagreement; a deadlock."
    "Impecunious|/ˌɪmpɪˈkjuːniəs/|adj.|Having little or no money."
    "Inexorable|/ɪnˈɛksərəbəl/|adj.|Impossible to stop or prevent."
    "Insipid|/ɪnˈsɪpɪd/|adj.|Lacking vigor or interest."
    "Intransigent|/ɪnˈtrænsɪdʒənt/|adj.|Unwilling or refusing to change one's views or to agree about something."
    "Mendacious|/mɛnˈdeɪʃəs/|adj.|Not telling the truth; lying."
    "Mercurial|/mərˈkjʊəriəl/|adj.|(Of a person) subject to sudden or unpredictable changes of mood or mind."
    "Meticulous|/mɪˈtɪkjələs/|adj.|Showing great attention to detail; very careful and precise."
    "Mollify|/ˈmɒlɪfaɪ/|v.|Appease the anger or anxiety of (someone)."
    "Noxious|/ˈnɒkʃəs/|adj.|Harmful, poisonous, or very unpleasant."
    "Obfuscate|/ˈɒbfəskeɪt/|v.|Render obscure, unclear, or unintelligible."
    "Paean|/ˈpiːən/|n.|A song of praise or triumph."
      "Panacea|/ˌpænəˈsiːə/|n.|A solution or remedy for all difficulties or diseases."
      "Paragon|/ˈpærəɡɒn/|n.|A person or thing regarded as a perfect example of a particular quality."
      "Penury|/ˈpɛnjʊri/|n.|The state of being very poor; extreme poverty."
      "Pernicious|/pərˈnɪʃəs/|adj.|Having a harmful effect, especially in a gradual or subtle way."
      "Plethora|/ˈplɛθərə/|n.|An excessive amount of something."
      "Portentous|/pɔːrˈtɛntəs/|adj.|Of or like a portent (an omen); ominous; done in a pompously or overly solemn manner."
      "Pragmatic|/præɡˈmætɪk/|adj.|Dealing with things sensibly and realistically in a way that is based on practical rather than theoretical considerations."
      "Profligate|/ˈprɒflɪɡət/|adj.|Recklessly extravagant or wasteful in the use of resources."
      "Pugnacious|/pʌɡˈneɪʃəs/|adj.|Eager or quick to argue, quarrel, or fight."
      "Quandary|/ˈkwɒndəri/|n.|A state of perplexity or uncertainty over what to do in a difficult situation."
      "Quotidian|/kwɒˈtɪdiən/|adj.|Of or occurring every day; daily; commonplace."
      "Rancor|/ˈræŋkər/|n.|Bitterness or resentfulness, especially when long-standing."
      "Rhetoric|/ˈrɛtərɪk/|n.|The art of effective or persuasive speaking or writing, especially the use of figures of speech and other compositional techniques."
      "Sanctimonious|/ˌsæŋktɪˈmoʊniəs/|adj.|Making a show of being morally superior to other people."
      "Solipsism|/ˈsɒlɪpsɪzəm/|n.|The view or theory that the self is all that can be known to exist."
      "Superfluous|/suːˈpɜːrfluəs/|adj.|Unnecessary, especially through being more than enough."
      "Sybaritic|/ˌsɪbəˈrɪtɪk/|adj.|Fond of sensuous luxury or self-indulgence."
      "Temerity|/tɪˈmɛrəti/|n.|Excessive confidence or boldness; audacity."
      "Tenuous|/ˈtɛnjuəs/|adj.|Very weak or slight."
      "Ubiquitous|/juːˈbɪkwɪtəs/|adj.|Present, appearing, or found everywhere."
      "Vacillate|/ˈvæsɪleɪt/|v.|Alternate or waver between different opinions or actions; be indecisive."
      "Venerable|/ˈvɛnərəbəl/|adj.|Accorded a great deal of respect, especially because of age, wisdom, or character."
      "Veracity|/vəˈræsɪti/|n.|Conformity to facts; accuracy."
      "Vernacular|/vərˈnækjʊlər/|n.|The language or dialect spoken by the ordinary people in a particular country or region."
      "Vex|/vɛks/|v.|Make (someone) feel annoyed, frustrated, or worried, especially with trivial matters."
      "Vitiate|/ˈvɪʃieɪt/|v.|Spoil or impair the quality or efficiency of."
      "Vituperate|/vɪˈtuːpəreɪt/|v.|Blame or insult (someone) in strong or violent language."
      "Wistful|/ˈwɪstfəl/|adj.|Having or showing a feeling of vague or regretful longing."
      "Xenophobia|/ˌzɛnəˈfoʊbiə/|n.|Intense or irrational dislike or fear of people from other countries."
      "Yore|/jɔːr/|n.|Of long ago or former times (used in nostalgic or historical context)."
      "Abscond|/æbˈskɒnd/|v.|Leave hurriedly and secretly, typically to escape from custody or avoid arrest."
      "Abstemious|/æbˈstiːmiəs/|adj.|Not self-indulgent, especially when eating and drinking."
      "Ascetic|/əˈsɛtɪk/|adj.|Characterized by severe self-discipline and abstention from all forms of indulgence, typically for religious reasons."
      "Bellicose|/ˈbɛlɪkoʊs/|adj.|Demonstrating aggression and willingness to fight."
      "Brobdingnagian|/ˌbrɒbdɪŋˈnædʒiən/|adj.|Gigantic."
      "Chicanery|/ʃɪˈkeɪnəri/|n.|The use of deception or trickery."
      "Circumlocution|/ˌsɜːrkəmləˈkjuːʃən/|n.|The use of many words where fewer would do, especially in a deliberate attempt to be vague or evasive."
      "Concomitant|/kənˈkɒmɪtənt/|adj.|Naturally accompanying or associated."
      "Conflagration|/ˌkɒnfləˈɡreɪʃən/|n.|An extensive fire that destroys a great deal of land or property."
      "Corpulent|/ˈkɔːrpjʊlənt/|adj.|(Of a person) fat."
      "Diatribe|/ˈdaɪətraɪb/|n.|A forceful and bitter verbal attack against someone or something."
      "Diffident|/ˈdɪfɪdənt/|adj.|Modest or shy because of a lack of self-confidence."
        "Discursive|/dɪˈskɜːrsɪv/|adj.|Digressing from subject to subject."
        "Egocentric|/ˌiːɡoʊˈsɛntrɪk/|adj.|Thinking only of oneself, without regard for the feelings or desires of others; self-centered."
        "Eldritch|/ˈɛldrɪtʃ/|adj.|Strange and frightening."
        "Emollient|/ɪˈmɒliənt/|adj.|Having the quality of softening or soothing the skin; making something smoother or less harsh."
        "Ephemeral|/ɪˈfɛmərəl/|adj.|Lasting for a very short time."
        "Equanimity|/ˌɛkwəˈnɪmɪti/|n.|Calmness and composure, especially in a difficult situation."
        "Eschew|/ɪsˈtʃuː/|v.|Deliberately avoid using; abstain from."
        "Fecund|/ˈfɛkənd/|adj.|Producing or capable of producing an abundance of offspring or new growth; fertile."
        "Feral|/ˈfɛrəl/|adj.|(Especially of an animal) in a wild state, especially after escape from captivity or domestication."
        "Flummox|/ˈflʌməks/|v.|Perplex (someone) deeply; bewilder."
        "Gesticulate|/dʒɛˈstɪkjʊleɪt/|v.|Use gestures, especially dramatic ones, instead of speaking or to emphasize one's words."
        "Hapless|/ˈhæplɪs/|adj.|(Especially of a person) unfortunate."
        "Iconoclast|/aɪˈkɒnəklæst/|n.|A person who attacks cherished beliefs or institutions."
        "Idiosyncrasy|/ˌɪdiəˈsɪŋkrəsi/|n.|A mode of behavior or way of thought peculiar to an individual."
        "Impudent|/ˈɪmpjʊdənt/|adj.|Not showing due respect for another person; impertinent."
        "Indefatigable|/ˌɪndɪˈfætɪɡəbəl/|adj.|(Of a person or their efforts) persisting tirelessly."
        "Ineffable|/ɪnˈɛfəbəl/|adj.|Too great or extreme to be expressed or described in words."
        "Jubilant|/ˈdʒuːbɪlənt/|adj.|Feeling or expressing great happiness and triumph."
        "Kismet|/ˈkɪsmɛt/|n.|Destiny; fate."
        "Labyrinthine|/ˌlæbərɪnˈθaɪn/|adj.|(Of a network of paths and passages) intricate and confusing."
        "Lambent|/ˈlæmbənt/|adj.|(Of light or fire) softly bright or radiant; (of wit or humor) playfully brilliant."
        "Lilt|/lɪlt/|n.|A characteristic rising and falling of the voice in speaking; a pleasant gentle accent."
        "Lissome|/ˈlɪsəm/|adj.|(Of a person or their body) thin, supple, and graceful."
        "Lugubrious|/luːˈɡuːbriəs/|adj.|Looking or sounding sad and dismal."
        "Maverick|/ˈmævərɪk/|n.|An unorthodox or independent-minded person."
        "Miasma|/miˈæzmə/|n.|An unpleasant or unhealthy smell or vapor; an oppressive or unpleasant atmosphere."
        "Minatory|/ˈmɪnətəri/|adj.|Expressing or conveying a threat."
        "Niggle|/ˈnɪɡəl/|v.|Cause slight but persistent annoyance, discomfort, or anxiety."
        "Numinous|/ˈnjuːmɪnəs/|adj.|Having a strong religious or spiritual quality; indicating or suggesting the presence of a divinity."
        "Obdurate|/ˈɒbdjʊrət/|adj.|Stubbornly refusing to change one's opinion or course of action."
        "Onerous|/ˈɒnərəs/|adj.|(Of a task, duty, or responsibility) involving an amount of effort and difficulty that is oppressively burdensome."
        "Ostentatious|/ˌɒstɛnˈteɪʃəs/|adj.|Characterized by vulgar or pretentious display; designed to impress or attract notice."
        "Palimpsest|/ˈpælɪmpsɛst/|n.|A manuscript or piece of writing material on which the original writing has been effaced to make room for later writing but of which traces remain."
        "Panoply|/ˈpænəpli/|n.|A complete or impressive collection of things; a magnificent display."
        "Paradox|/ˈpærədɒks/|n.|A seemingly absurd or self-contradictory statement or proposition that when investigated or explained may prove to be well founded or true."
        "Parsimonious|/ˌpɑːrsɪˈmoʊniəs/|adj.|Unwilling to spend money or use resources; stingy or frugal."
        "Pedantic|/pɪˈdæntɪk/|adj.|Excessively concerned with minor details and rules; overscrupulous."
        "Philistine|/ˈfɪlɪstaɪn/|n.|A person who is hostile or indifferent to culture and the arts, or who has no understanding of them."
        "Phlegmatic|/flɛɡˈmætɪk/|adj.|(Of a person) having an unemotional and stolidly calm disposition."
        "Pique|/piːk/|v.|Stimulate (interest or curiosity); feel irritated or resentful."
          "Ponderous|/ˈpɒndərəs/|adj.|Slow and clumsy because of great weight; dull, laborious, or excessively solemn."
          "Pusillanimous|/ˌpjuːsɪˈlænɪməs/|adj.|Showing a lack of courage or determination; timid."
          "Rapt|/ræpt/|adj.|Completely engrossed by what one is seeing or hearing."
          "Replete|/rɪˈpliːt/|adj.|Filled or well-supplied with something."
          "Reticent|/ˈrɛtɪsənt/|adj.|Not revealing one's thoughts or feelings readily."
          "Ruminant|/ˈruːmɪnənt/|adj.|(Of an animal) chewing the cud; (of a person) thoughtful or meditative."
          "Sartorial|/sɑːrˈtɔːriəl/|adj.|Of or relating to tailoring, clothes, or style of dress."
          "Sentient|/ˈsɛnʃɪənt/|adj.|Able to perceive or feel things."
          "Somnambulist|/sɒmˈnæmbjʊlɪst/|n.|A person who walks in their sleep."
          "Sophistry|/ˈsɒfɪstri/|n.|The use of clever but false arguments, especially with the intention of deceiving."
          "Specious|/ˈspiːʃəs/|adj.|Superficially plausible, but actually wrong."
        )
        
        # Example of how to iterate through the list and print details:
        echo "Total interesting words: ${#interesting_words[@]}"
        echo "--------------------------------------------------"
        
        # Loop through each item in the array
        for item in "${interesting_words[@]}"; do
          # Use IFS (Internal Field Separator) to split the string by '|'
          IFS='|' read -r word phonetic type meaning <<< "$item"
        
          echo "Word:     $word"
          echo "Phonetic: $phonetic"
          echo "Type:     $type"
          echo "Meaning:  $meaning"
          echo "--------------------------------------------------"
        done
#        ```
