#!/bin/bash
########### Here's a list of 122 interesting English words, formatted as a bash array. Each element in the `interesting_words` array is a string containing the word, its phonetic transcription (IPA), its part of speech (type), and its meaning, separated by `|` characters.
###########
# This array contains a list of interesting English words.
# Each element is formatted as "Word|Phonetic|Type|Meaning".
# The phonetic transcriptions are in IPA (International Phonetic Alphabet).
# Type abbreviations: n. (noun), v. (verb), adj. (adjective), adv. (adverb).
declare -a interesting_words=(
"Abscond|/æbˈskɒnd/|verb.|Leave hurriedly and secretly, typically to escape from custody or avoid arrest."
"Abstemious|/æbˈstiːmiəs/|adj.|noun.t self-indulgent, especially when eating and drinking."
"Alacrity|/əˈlækrɪti/|noun.|Brisk and cheerful readiness."
"Ameliorate|/əˈmiːljəreɪt/|verb.|Make (something bad or unsatisfactory) better."
"Ascetic|/əˈsɛtɪk/|adj.|Characterized by severe self-discipline and abstention from all forms of indulgence, typically for religious reasons."
"Aurora|/ɔːˈrɔːrə/|noun.|A natural electrical phenomenon characterized by the appearance of streamers of reddish or greenish light in the sky, especially near the northern or southern magnetic poles."
"Bellicose|/ˈbɛlɪkoʊs/|adj.|Demonstrating aggression and willingness to fight."
"Brobdingnagian|/ˌbrɒbdɪŋˈnædʒiən/|adj.|Gigantic."
"Cacophony|/kəˈkɒfəni/|noun.|A harsh, discordant mixture of sounds."
"Capricious|/kəˈprɪʃəs/|adj.|Given to sudden and unaccountable changes of mood or behavior."
"Chicanery|/ʃɪˈkeɪnəri/|noun.|The use of deception or trickery."
"Circumlocution|/ˌsɜːrkəmləˈkjuːʃən/|noun.|The use of many words where fewer would do, especially in a deliberate attempt to be vague or evasive."
"Clandestine|/klænˈdɛstɪn/|adj.|Kept secret or done secretively, especially because illicit."
"Concomitant|/kənˈkɒmɪtənt/|adj.|noun.turally accompanying or associated."
"Conflagration|/ˌkɒnfləˈɡreɪʃən/|noun.|An extensive fire that destroys a great deal of land or property."
"Convivial|/kənˈvɪviəl/|adj.|(Of an atmosphere or event) friendly, lively, and enjoyable; (of a person) cheerful and friendly."
"Corpulent|/ˈkɔːrpjʊlənt/|adj.|(Of a person) fat."
"Crepuscular|/krɪˈpʌskjələr/|adj.|Of, relating to, or resembling twilight; active in the twilight."
"Deleterious|/ˌdɛlɪˈtɪəriəs/|adj.|Causing harm or damage."
"Desultory|/ˈdɛsəltəri/|adj.|Lacking a plan, purpose, or enthusiasm; aimless."
"Diatribe|/ˈdaɪətraɪb/|noun.|A forceful and bitter verbal attack against someone or something."
"Diffident|/ˈdɪfɪdənt/|adj.|Modest or shy because of a lack of self-confidence."
"Discursive|/dɪˈskɜːrsɪv/|adj.|Digressing from subject to subject."
"Disparate|/ˈdɪspərət/|adj.|Essentially different in kind; not able to be compared."
"Egocentric|/ˌiːɡoʊˈsɛntrɪk/|adj.|Thinking only of oneself, without regard for the feelings or desires of others; self-centered."
"Egregious|/ɪˈɡriːdʒəs/|adj.|Outstandingly bad; shocking."
"Eldritch|/ˈɛldrɪtʃ/|adj.|Strange and frightening."
"Emollient|/ɪˈmɒliənt/|adj.|Having the quality of softening or soothing the skin; making something smoother or less harsh."
"Enervate|/ˈɛnərveɪt/|verb.|Cause (someone) to feel drained of energy or vitality; weaken."
"Ephemeral|/ɪˈfɛmərəl/|adj.|Lasting for a very short time."
"Ephemeral|/ɪˈfɛmərəl/|adj.|Lasting for a very short time."
"Equanimity|/ˌɛkwəˈnɪmɪti/|noun.|Calmness and composure, especially in a difficult situation."
"Equivocate|/ɪˈkwɪvəkeɪt/|verb.|Use ambiguous language so as to conceal the truth or avoid committing oneself."
"Eschew|/ɪsˈtʃuː/|verb.|Deliberately avoid using; abstain from."
"Ethereal|/ɪˈθɪəriəl/|adj.|Extremely delicate and light in a way that seems too perfect for this world."
"Euphony|/ˈjuːfəni/|noun.|The quality of being pleasing to the ear, especially through a harmonious combination of words."
"Expurgate|/ˈɛkspərɡeɪt/|verb.|Remove objectionable passages or words from (a book or account)."
"Fastidious|/fæsˈtɪdiəs/|adj.|verb.ry attentive to and concerned about accuracy and detail; hard to please."
"Fatuous|/ˈfætjuəs/|adj.|Silly and pointless."
"Fecund|/ˈfɛkənd/|adj.|Producing or capable of producing an abundance of offspring or new growth; fertile."
"Feral|/ˈfɛrəl/|adj.|(Especially of an animal) in a wild state, especially after escape from captivity or domestication."
"Flummox|/ˈflʌməks/|verb.|Perplex (someone) deeply; bewilder."
"Garrulous|/ˈɡærʊləs/|adj.|Excessively talkative, especially on trivial matters."
"Gesticulate|/dʒɛˈstɪkjʊleɪt/|verb.|Use gestures, especially dramatic ones, instead of speaking or to emphasize one's words."
"Gregarious|/ɡrɪˈɡɛəriəs/|adj.|(Of a person) fond of company; sociable."
"Halcyon|/ˈhælsɪən/|adj.|Denoting a period of time in the past that was idyllically happy and peaceful."
"Hapless|/ˈhæplɪs/|adj.|(Especially of a person) unfortunate."
"Harangue|/həˈræŋ/|noun.|A lengthy and aggressive speech."
"Hegemony|/hɪˈdʒɛməni/|noun.|Leadership or dominance, especially by one state or social group over others."
"Iconoclast|/aɪˈkɒnəklæst/|noun.|A person who attacks cherished beliefs or institutions."
"Idiosyncrasy|/ˌɪdiəˈsɪŋkrəsi/|noun.|A mode of behavior or way of thought peculiar to an individual."
"Ignominious|/ˌɪɡnəˈmɪniəs/|adj.|Deserving or causing public disgrace or shame."
"Impasse|/ˈɪmpæs/|noun.|A situation in which no progress is possible, especially because of disagreement; a deadlock."
"Impecunious|/ˌɪmpɪˈkjuːniəs/|adj.|Having little or no money."
"Impudent|/ˈɪmpjʊdənt/|adj.|noun.t showing due respect for another person; impertinent."
"Incipient|/ɪnˈsɪpiənt/|adj.|In an initial stage; beginning to happen or develop."
"Indefatigable|/ˌɪndɪˈfætɪɡəbəl/|adj.|(Of a person or their efforts) persisting tirelessly."
"Ineffable|/ɪnˈɛfəbəl/|adj.|Too great or extreme to be expressed or described in words."
"Inexorable|/ɪnˈɛksərəbəl/|adj.|Impossible to stop or prevent."
"Innocuous|/ɪˈnɒkjuəs/|adj.|noun.t harmful or offensive."
"Insipid|/ɪnˈsɪpɪd/|adj.|Lacking vigor or interest."
"Intransigent|/ɪnˈtrænsɪdʒənt/|adj.|Unwilling or refusing to change one's views or to agree about something."
"Jubilant|/ˈdʒuːbɪlənt/|adj.|Feeling or expressing great happiness and triumph."
"Kismet|/ˈkɪsmɛt/|noun.|Destiny; fate."
"Labyrinthine|/ˌlæbərɪnˈθaɪn/|adj.|(Of a network of paths and passages) intricate and confusing."
"Laconic|/ləˈkɒnɪk/|adj.|(Of a person, speech, or style of writing) using very few words."
"Lambent|/ˈlæmbənt/|adj.|(Of light or fire) softly bright or radiant; (of wit or humor) playfully brilliant."
"Languid|/ˈlæŋɡwɪd/|adj.|(Of a person, manner, or gesture) having a disinclination for physical exertion or effort; slow and relaxed."
"Lilt|/lɪlt/|noun.|A characteristic rising and falling of the voice in speaking; a pleasant gentle accent."
"Limerence|/ˈlɪmərəns/|noun.|The state of being infatuated with another person, typically involuntarily and characterized by a desire for reciprocation."
"Lissome|/ˈlɪsəm/|adj.|(Of a person or their body) thin, supple, and graceful."
"Lugubrious|/luːˈɡuːbriəs/|adj.|Looking or sounding sad and dismal."
"Luminescence|/ˌluːmɪˈnɛsəns/|noun.|The emission of light by a substance not resulting from heat; light from a chemical or biological reaction."
"Magnanimous|/mæɡˈnænɪməs/|adj.|Generous or forgiving, especially toward a rival or less powerful person."
"Maverick|/ˈmævərɪk/|noun.|An unorthodox or independent-minded person."
"Mellifluous|/mɛˈlɪfluəs/|adj.|(Of a voice or words) sweet or musical; pleasant to hear."
"Mendacious|/mɛnˈdeɪʃəs/|adj.|noun.t telling the truth; lying."
"Mercurial|/mərˈkjʊəriəl/|adj.|(Of a person) subject to sudden or unpredictable changes of mood or mind."
"Meticulous|/mɪˈtɪkjələs/|adj.|Showing great attention to detail; very careful and precise."
"Miasma|/miˈæzmə/|noun.|An unpleasant or unhealthy smell or vapor; an oppressive or unpleasant atmosphere."
"Minatory|/ˈmɪnətəri/|adj.|Expressing or conveying a threat."
"Mollify|/ˈmɒlɪfaɪ/|verb.|Appease the anger or anxiety of (someone)."
"Nadir|/ˈneɪdɪər/|noun.|The lowest point in the fortunes of a person or organization."
"Nascent|/ˈnæsənt/|adj.|(Especially of a social phenomenon) just coming into existence and beginning to display signs of future potential."
"Nefarious|/nɪˈfɛəriəs/|adj.|(Typically of an action or activity) wicked or criminal."
"Niggle|/ˈnɪɡəl/|verb.|Cause slight but persistent annoyance, discomfort, or anxiety."
"Noxious|/ˈnɒkʃəs/|adj.|Harmful, poisonous, or very unpleasant."
"Numinous|/ˈnjuːmɪnəs/|adj.|Having a strong religious or spiritual quality; indicating or suggesting the presence of a divinity."
"Obdurate|/ˈɒbdjʊrət/|adj.|Stubbornly refusing to change one's opinion or course of action."
"Obfuscate|/ˈɒbfəskeɪt/|verb.|Render obscure, unclear, or unintelligible."
"Obsequious|/əbˈsiːkwiəs/|adj.|Excessively obedient or attentive to an excessive degree."
"Obstreperous|/əbˈstrɛpərəs/|adj.|noun.isy and difficult to control."
"Onerous|/ˈɒnərəs/|adj.|(Of a task, duty, or responsibility) involving an amount of effort and difficulty that is oppressively burdensome."
"Ostentatious|/ˌɒstɛnˈteɪʃəs/|adj.|Characterized by vulgar or pretentious display; designed to impress or attract notice."
"Paean|/ˈpiːən/|noun.|A song of praise or triumph."
"Palimpsest|/ˈpælɪmpsɛst/|noun.|A manuscript or piece of writing material on which the original writing has been effaced to make room for later writing but of which traces remain."
"Panacea|/ˌpænəˈsiːə/|noun.|A solution or remedy for all difficulties or diseases."
"Panoply|/ˈpænəpli/|noun.|A complete or impressive collection of things; a magnificent display."
"Paradox|/ˈpærədɒks/|noun.|A seemingly absurd or self-contradictory statement or proposition that when investigated or explained may prove to be well founded or true."
"Paragon|/ˈpærəɡɒn/|noun.|A person or thing regarded as a perfect example of a particular quality."
"Parsimonious|/ˌpɑːrsɪˈmoʊniəs/|adj.|Unwilling to spend money or use resources; stingy or frugal."
"Pedantic|/pɪˈdæntɪk/|adj.|Excessively concerned with minor details and rules; overscrupulous."
"Pellucid|/pəˈluːsɪd/|adj.|Translucently clear; easily understood."
"Penultimate|/pɪˈnʌltɪmət/|adj.|Last but one in a series of things; second to last."
"Penury|/ˈpɛnjʊri/|noun.|The state of being very poor; extreme poverty."
"Perfunctory|/pəˈfʌŋktəri/|adj.|(Of an action or gesture) carried out with a minimum of effort or reflection."
"Pernicious|/pərˈnɪʃəs/|adj.|Having a harmful effect, especially in a gradual or subtle way."
"Petrichor|/ˈpɛtrɪkɔːr/|noun.|The distinctive smell of rain on dry earth."
"Philistine|/ˈfɪlɪstaɪn/|noun.|A person who is hostile or indifferent to culture and the arts, or who has no understanding of them."
"Phlegmatic|/flɛɡˈmætɪk/|adj.|(Of a person) having an unemotional and stolidly calm disposition."
"Pique|/piːk/|verb.|Stimulate (interest or curiosity); feel irritated or resentful."
"Plethora|/ˈplɛθərə/|noun.|An excessive amount of something."
"Ponderous|/ˈpɒndərəs/|adj.|Slow and clumsy because of great weight; dull, laborious, or excessively solemn."
"Portentous|/pɔːrˈtɛntəs/|adj.|Of or like a portent (an omen); ominous; done in a pompously or overly solemn manner."
"Pragmatic|/præɡˈmætɪk/|adj.|Dealing with things sensibly and realistically in a way that is based on practical rather than theoretical considerations."
"Prevaricate|/prɪˈværɪkeɪt/|verb.|Speak or act in an evasive way."
"Profligate|/ˈprɒflɪɡət/|adj.|Recklessly extravagant or wasteful in the use of resources."
"Pugnacious|/pʌɡˈneɪʃəs/|adj.|Eager or quick to argue, quarrel, or fight."
"Punctilious|/pʌŋkˈtɪliəs/|adj.|Showing great attention to detail or correct behavior."
"Pusillanimous|/ˌpjuːsɪˈlænɪməs/|adj.|Showing a lack of courage or determination; timid."
"Quandary|/ˈkwɒndəri/|noun.|A state of perplexity or uncertainty over what to do in a difficult situation."
"Quiescent|/kwiˈɛsənt/|adj.|In a state or period of inactivity or dormancy."
"Quixotic|/kwɪkˈsɒtɪk/|adj.|Exceedingly idealistic; unrealistic and impractical."
"Quotidian|/kwɒˈtɪdiən/|adj.|Of or occurring every day; daily; commonplace."
"Rancor|/ˈræŋkər/|noun.|Bitterness or resentfulness, especially when long-standing."
"Rapt|/ræpt/|adj.|Completely engrossed by what one is seeing or hearing."
"Recalcitrant|/rɪˈkælsɪtrənt/|adj.|Having an obstinately uncooperative attitude toward authority or discipline."
"Recondite|/ˈrɛkəndaɪt/|adj.|(Of a subject or knowledge) little known; abstruse."
"Replete|/rɪˈpliːt/|adj.|Filled or well-supplied with something."
"Repudiate|/rɪˈpjuːdieɪt/|verb.|Refuse to accept or be associated with; deny the truth or validity of."
"Reticent|/ˈrɛtɪsənt/|adj.|noun.t revealing one's thoughts or feelings readily."
"Rhetoric|/ˈrɛtərɪk/|noun.|The art of effective or persuasive speaking or writing, especially the use of figures of speech and other compositional techniques."
"Ruminant|/ˈruːmɪnənt/|adj.|(Of an animal) chewing the cud; (of a person) thoughtful or meditative."
"Sagacious|/səˈɡeɪʃəs/|adj.|Having or showing keen mental discernment and good judgment; shrewd."
"Salient|/ˈseɪliənt/|adj.|Most noticeable or important."
"Sanctimonious|/ˌsæŋktɪˈmoʊniəs/|adj.|Making a show of being morally superior to other people."
"Sanguine|/ˈsæŋɡwɪn/|adj.|Optimistic or positive, especially in an apparently bad or difficult situation."
"Sartorial|/sɑːrˈtɔːriəl/|adj.|Of or relating to tailoring, clothes, or style of dress."
"Scintilla|/sɪnˈtɪlə/|noun.|A tiny trace or spark of a specified quality or feeling."
"Sentient|/ˈsɛnʃɪənt/|adj.|Able to perceive or feel things."
"Serendipity|/ˌsɛrənˈdɪpɪti/|noun.|The occurrence and development of events by chance in a happy or beneficial way."
"Solipsism|/ˈsɒlɪpsɪzəm/|noun.|The view or theory that the self is all that can be known to exist."
"Somnambulist|/sɒmˈnæmbjʊlɪst/|noun.|A person who walks in their sleep."
"Sonder|/ˈsɒndər/|noun.|The realization that each random passerby is living a life as vivid and complex as your own."
"Sophistry|/ˈsɒfɪstri/|noun.|The use of clever but false arguments, especially with the intention of deceiving."
"Specious|/ˈspiːʃəs/|adj.|Superficially plausible, but actually wrong."
"Stentorian|/stɛnˈtɔːriən/|adj.|(Of a person's voice) loud and powerful."
"Superfluous|/suːˈpɜːrfluəs/|adj.|Unnecessary, especially through being more than enough."
"Surreptitious|/ˌsʌrəpˈtɪʃəs/|adj.|Kept secret, especially because it would not be approved of."
"Sybaritic|/ˌsɪbəˈrɪtɪk/|adj.|Fond of sensuous luxury or self-indulgence."
"Taciturn|/ˈtæsɪtɜːrn/|adj.|(Of a person) reserved or uncommunicative in speech; saying little."
"Temerity|/tɪˈmɛrəti/|noun.|Excessive confidence or boldness; audacity."
"Tenuous|/ˈtɛnjuəs/|adj.|verb.ry weak or slight."
"Truculent|/ˈtrʌkjʊlənt/|adj.|Eager or quick to argue or fight; aggressively defiant."
"Ubiquitous|/juːˈbɪkwɪtəs/|adj.|Present, appearing, or found everywhere."
"Ubiquitous|/juːˈbɪkwɪtəs/|adj.|Present, appearing, or found everywhere."
"Uxorious|/ʌkˈsɔːriəs/|adj.|Having or showing an excessive fondness for one's wife."
"Vacillate|/ˈvæsɪleɪt/|verb.|Alternate or waver between different opinions or actions; be indecisive."
"Venerable|/ˈvɛnərəbəl/|adj.|Accorded a great deal of respect, especially because of age, wisdom, or character."
"Veracity|/vəˈræsɪti/|noun.|Conformity to facts; accuracy."
"Vernacular|/vərˈnækjʊlər/|noun.|The language or dialect spoken by the ordinary people in a particular country or region."
"Vex|/vɛks/|verb.|Make (someone) feel annoyed, frustrated, or worried, especially with trivial matters."
"Vicarious|/vɪˈkɛəriəs/|adj.|Experienced in the imagination through the feelings or actions of another person."
"Vicissitude|/vɪˈsɪsɪtjuːd/|noun.|A change of circumstances or fortune, typically one that is unwelcome or unpleasant."
"Vitiate|/ˈvɪʃieɪt/|verb.|Spoil or impair the quality or efficiency of."
"Vituperate|/vɪˈtuːpəreɪt/|verb.|Blame or insult (someone) in strong or violent language."
"Winsome|/ˈwɪnsəm/|adj.|Attractive or appealing in a fresh, innocent way."
"Wistful|/ˈwɪstfəl/|adj.|Having or showing a feeling of vague or regretful longing."
"Xenophobia|/ˌzɛnəˈfoʊbiə/|noun.|Intense or irrational dislike or fear of people from other countries."
"Yore|/jɔːr/|noun.|Of long ago or former times (used in nostalgic or historical context)."
"Zenith|/ˈzɛnɪθ/|noun.|The point in the sky or celestial sphere directly above an observer; the time at which something is most powerful or successful."
"Zephyr|/ˈzɛfər/|noun.|A soft, gentle breeze."
)        
# Example of how to iterate through the list and print details:
echo "Total interesting words: ${#interesting_words[@]}"
echo "--------------------------------------------------"        
# Loop through each item in the array
for item in "${interesting_words[@]}"; do
# Use IFS (Internal Field Separator) to split the string by '|'
IFS='|' read -r word phonetic type meaning <<< "$item"        
echo "$word"
echo "[$phonetic]"
echo "$type"
echo "$meaning"
echo "--------------------------------------------------"
done
