#!/bin/bash
## install config-files 
[ -z "$start" ] && start="$HOME/zz"; 
hash sudo 2>/dev/null && [ "$UID" != "0" ] && sudo="sudo"; 
c2='    \e[0m\e[36m--\e[0m'; qq="160"; 
mkdir ~/.config 2>/dev/null; 
####
p1() { p2=" ${@}"; for i in $(seq ${#p2}); 
do sleep ${sl-.1}; printf %b "${p2:${i}:1}"; done; }; 
####
printf %b "\n$c2 installing config files ...\n"; 
$sudo ln -s ${PREFIX}/bin/bat ${PREFIX}/bin/batcat &>/dev/null; 
$sudo ln -s ${PREFIX}/bin/batcat ${PREFIX}/bin/bat &>/dev/null; 
##
ln -s $start/c/inputrc $HOME/.inputrc --backup --suffix=_bu$(date +%y%m%d_%H%M%S); 
ln -s $start/c/lesskey $start/c/*.conf -t $HOME/.config --backup --suffix="_bu$(date +%y%m%d_%H%M%S)"; 
##
confolders=($(command ls -1p $start/c|grep "/")); 
for q in ${confolders[*]}; do 
mkdir -p $HOME/.config/$q 2>/dev/null; 
mv $HOME/.config/$q/* -t $HOME/tmp -b --suffix="_bu$(date +%y%m%d_%H%M%S)" 2>/dev/null; 
ln -s $start/c/$q/* -t $HOME/.config/$q/ --backup --suffix="_bu$(date +%y%m%d_%H%M%S)"; 
sleep .1; 
printf %b "\n\e[0m"; p1 "updated"; 
printf %b "\e[38;5;$((qq++))m $q"; 
done; 
mkdir -p $HOME/bin -m 775 2>/dev/null; 
ln -s $start/c/ssss.sh $HOME/bin/ssss 2>/dev/null; 
printf %b "${PATH}:${HOME}/.local/bin:${HOME}/bin" > $HOME/.config/path.sh; 
chmod 775 $HOME/.config/path.sh; 
printf %b "\n\e[0m\n"; 
p1 'added PATH to ~/.config/path.sh '; 
printf %b "\n\n$c2 config files installed! \n\n"; 
