#!/bin/bash
## create super user froom root
# sus() { sudo $@; }; 
IFS=$'\n\t '; c2='\e[96m--\e[0m'; 
unalias sudo 2>/dev/null; unset sudo; # 2>/dev/null; 
sudo mkdir -pm 775 /home/${SUDO_USER:-$USER}/tmp; # 2>/dev/null; 
sudo chown ${SUDO_USER:-$USER}: /home/${SUDO_USER:-$USER}/tmp; # 2>/dev/null; 
# hash sudo 2>/dev/null && 
if ((UID > 1)); then printf %b "\n $c2 \e[2m[\e[0m $0 \e[0m]\n $c2 run this as sudo\n\n\n\n"; 
echo; [[ $0 =~ /*/ ]] && exit 1; 
[[ $0 =~ -bash ]]||return 5 2>/dev/null; else 
printf %b "\n\n\n\n\e[2A $c2 Add as sudo-user: "; 
read -ep ' ' -i "${SUDO_USER:-$USER}" "newsudo"; 
####
touch /etc/sudoers.d/$newsudo; 
chmod 775 /etc/sudoers.d/$newsudo; 
####
sds=($(touch /etc/sudoers.d/$newsudo 2>&1|sed -n "/\(error\|empty\)/p"|cut -f2 -d":")); 
[ $sds ] && sed $(for ss in ${sds[*]}; do printf %b "-e ${ss}d "; done) /etc/sudoers.d/$newsudo > /home/$SUDO_USER/tmp/$newsudo; 
####
[ -s /home/${SUDO_USER:-$USER}/tmp/$newsudo ] || cp /home/${SUDO_USER:-$USER}/tmp/$newsudo /etc/sudoers.d/$newsudo -b; 
####
echo;echo;echo;echo;
echo "${newsudo} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/$newsudo; 
echo "%${newsudo} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/$newsudo; 
cat /etc/sudoers.d/$newsudo; 
echo;echo;echo;echo;
####
####
# sds=($(sudo touch /etc/sudoers.d/sudos.sh 2>&1|sed -n "/\(error\|empty\)/p"|cut -f2 -d":")); 
# [ $sds ] && sed $(for ss in ${sds[*]}; do 
# printf %b "-e ${ss}d "; done) /etc/sudoers.d/sudos.sh > $HOME/sudos.sh; 
# sudo cp $HOME/sudos.sh /etc/sudoers.d/sudos.sh -b; 
####
####
printf %b "\n----\n\n $c2 DONE\n\n"; fi||return 6 2>/dev/null; 
# sudo=""; 
####
####
####
