[General]
__userfile__=true
backlightIdleness=31
backlightIdlenessOnBatteryDischarging=true
disableIdlenessWhenFullscreen=true
enableBatteryWatcher=true
enableExtMonLidClosedActions=false
enableIdlenessBacklightWatcher=true
enableIdlenessWatcher=true
enableLidWatcher=true
hibernateKeyAction=1
iconType=4
idlenessACAction=5
idlenessACTime=@Variant(\0\0\0\xf\0\r\xbb\xa0)
idlenessBatteryAction=1
idlenessBatteryTime=@Variant(\0\0\0\xf\0\r\xbb\xa0)
idlenessTime=@Variant(\0\0\0\xf\0\0\xea`)
lidClosedAcAction=5
lidClosedAction=1
lidClosedExtMonAcAction=-1
lidClosedExtMonAction=-1
powerKeyAction=6
powerLowAction=5
powerLowLevel=22
powerLowWarning=222
runCheckLevel=1
showIcon=true
suspendKeyAction=4
